# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build Docs

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  wiki:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      env:
        GAPI: ${{ secrets.GAPI_JSON }}
      run: |
        python -m pip install --upgrade pip
        if [ -f doc-requirements.txt ]; then pip install -r doc-requirements.txt; fi
        echo ${GAPI} > service.json
    - name: Build docs
      env:
        SPHINX: "sphinx"
      run: |
        pip install -r requirements.txt
        pip install -r sphinx/doc-requirements.txt
        sphinx-build -M html sphinx/source sphinx/build
        mkdir .github/wiki
        mv sphinx/build .github/wiki
        ls .github/wiki
    - uses: spenserblack/actions-wiki@v0.3.0
    

