# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Bot Launch Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      env:
        GAPI: ${{ secrets.GAPI_JSON }}
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        echo ${GAPI} > service.json
    - name: Test Python code
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        TEST_SERVER_ID: ${{ secrets.TEST_SERVER_ID }}
      run: |
        timeout --preserve-status 10s python bot.py || if [ $? -eq 143 ]; then echo "timeout closed the bot."; else exit 1; fi
    - name: Build docs
      env:
        SPHINX: "sphinx"
      run: |
        pip install -r sphinx/doc-requirements.txt
        sphinx-build -M markdown sphinx/source sphinx/build
        mkdir .github/wiki
        mv sphinx/build/markdown/index.md .github/wiki/Home.md
    - name: Upload docs
      uses: spenserblack/actions-wiki@v0.3.0
